name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.12

    - name: Fetch tags
      run: git fetch --tags

    - name: Remote fetch tags
      run: git fetch --tags https://github.com/teslamotors/vehicle-command.git

    - name: Debug information
      run: |
        git remote -v
        git branch -a
        git log --oneline
        git tag -l

    - name: No formatting changes
      run: |
        git tag
        make format
        git describe --tags --abbrev=0
        git diff --patch --stat
        git diff --exit-code

    - name: Test
      run: make test
